### ISSUE TITLE
McStasScript notebook repository

### ISSUE THREAD

**Issue by CFGrote** [PaNOSC-ViNYL/ViNYL-notebooks#2]
See #1. @mads-bertelsen, I added this here as a placeholder, not sure what (if anything) needs to be done to collect mcstasscript notebooks in a repo.

**Comment by mads-bertelsen** [comment]
Ok! So I will make a repository for McStasScript notebook examples and link as submodule.

**Comment by mads-bertelsen** [comment]
Pull request was made: https://github.com/PaNOSC-ViNYL/ViNYL-notebooks/pull/5
More notebooks will be added to the repository before the internal deadline.
